### ISSUE TITLE
Unstyled wikitable elements

### ISSUE THREAD

**Issue by Poorchop** [StylishThemes/Wikipedia-Dark#10]
[Unstyled element](https://en.wikipedia.org/wiki/Phineas_and_Ferb#Awards_and_nominations)

Wasn't sure where to go with this one either so I need a second opinion - I was thinking that the bright yellow header could be brown (#321) and the off-white rows could be #282828. I'm not sure about the brown as it might be better to just ignore the default yellow color and go for a more basic dark background variant.

**Comment by Mottie** [comment]
Yeah, brown looks good & the light yellow cells look good with #282828 as well.

I was thinking about maybe adding a basic zebra striping for all tables, but it definitely wouldn't work on that table. So maybe my idea isn't so great LOL.
