### ISSUE TITLE
Arch Linux Wiki Broken

### ISSUE THREAD

**Issue by leogx9r** [StylishThemes/Wikipedia-Dark#100]
Recently (unfortunately I don't know at what point since I only updated today after a few weeks), the entire Wiki at https://wiki.archlinux.org/ is broken -- background and link colors.

![Image](https://i.imgur.com/X8wExEO.png)

**Comment by the-j0k3r** [comment]
I think its this https://github.com/StylishThemes/Wikipedia-Dark/blob/42c6a3d92769648b72d81cc8c9f2a38a766e2fbd/wikipedia-dark.user.css#L40 that new rexep doesnt reach archwiki.

**Comment by AfroThundr3007730** [comment]
Ah, I should've used asterisks, one sec...

**Comment by the-j0k3r** [comment]
dont make a release yet please.
