### ISSUE TITLE
White background and borders

### ISSUE THREAD

**Issue by UweKeim** [StylishThemes/Wikipedia-Dark#101]
### Browser

Google Chrome, Version 80.0.3970.5 (Offizieller Build) dev (64-Bit)

### Operating System

Windows 10 German, 64-Bit

### Link to page with the issue

https://de.wikipedia.org/wiki/Raumh%C3%B6he#Deutschland

### Screenshot

![image](https://user-images.githubusercontent.com/415439/69641012-b1d9cd00-105f-11ea-8c2c-45c5cc1b7229.png)

**Comment by the-j0k3r** [comment]
A fix will be out momentarily. Thx for the report =)
