### ISSUE TITLE
italicized text is brighter than surrounding text

### ISSUE THREAD

**Issue by seansfkelley** [StylishThemes/Wikipedia-Dark#102]
* **Browser**: Firefox 70.0.1
* **Operating System**: macOS 10.15.1
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Naive_set_theory
* **Screenshot**:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/2101409/69654392-9358df00-1029-11ea-91d3-7a5094ac9100.png">

[Recent changes](https://github.com/StylishThemes/Wikipedia-Dark/commit/2376547dedfa7e4a20fffb2b16a044db32293d97#diff-c6b76bebc6d6643519e4e68ac9aa438aR1257) make it so every `<i>` element pops out from the darker `<p>` elements, which is distracting to read.

Compare with bolding, which does not change color:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/2101409/69654944-7bce2600-102a-11ea-8c7b-8e6fa91cb10d.png">

**Comment by the-j0k3r** [comment]
Please update to v2.3.38, thanks for report

**Comment by seansfkelley** [comment]
Thank you!
