### ISSUE TITLE
Bright TH backgrounds

### ISSUE THREAD

**Issue by UweKeim** [StylishThemes/Wikipedia-Dark#103]
Probably this isn't fixable, since the color seems to be hardcoded as an inline style:

```html
<th style="font-size:larger; background: #ccc;">
```

### Browser

Google Chrome Version 80.0.3970.5 (Offizieller Build) dev (64-Bit)

### Operating System

Windows 10, German, 64-bit

### Link to page with the issue

Several, e.g.:

- https://da.wikipedia.org/wiki/Tankestreg
- https://da.wikipedia.org/wiki/Punktum
- https://da.wikipedia.org/wiki/Dagger
- ...

### Screenshot

![image](https://user-images.githubusercontent.com/415439/69786458-c54d7b00-11ba-11ea-9bea-2bf13b9ac1c1.png)

**Comment by the-j0k3r** [comment]
It can be fixed, shortly. Thanks for reporting

**Comment by the-j0k3r** [comment]
Please [upgrade to v2.4.2](https://github.com/StylishThemes/Wikipedia-Dark/raw/master/wikipedia-dark.user.css) <- click
