### ISSUE TITLE
Background color of td overridden to gray

### ISSUE THREAD

**Issue by oowekyala** [StylishThemes/Wikipedia-Dark#104]
Hi, the colors of [this table](https://en.wikibooks.org/wiki/LaTeX/Colors#The_68_standard_colors_known_to_dvips) are overriden to gray. Example HTML:
```html
<td bgcolor="#FBB982">&nbsp;</td>
```

* **Browser**: Firefox 70.0.1
* **Operating System**: Ubuntu 16.04
* **Link to page with the issue**: https://en.wikibooks.org/wiki/LaTeX/Colors#The_68_standard_colors_known_to_dvips
* **Screenshot**:

  ![Capture du 2019-11-30 11-09-59](https://user-images.githubusercontent.com/24524930/69899132-56128b00-1362-11ea-8554-643175ef0d2e.png)

  ![Capture du 2019-11-30 11-12-58](https://user-images.githubusercontent.com/24524930/69899137-662a6a80-1362-11ea-98c7-09ac2b2ce794.png)

**Comment by the-j0k3r** [comment]
We have been fixing these lately and these were overridden intentionally as per https://github.com/StylishThemes/Wikipedia-Dark#limitations

Will be fixed whenever theres time. Thanks for report.

**Comment by the-j0k3r** [comment]
So[ click here to upgrade](https://github.com/StylishThemes/Wikipedia-Dark/raw/master/wikipedia-dark.user.css) to v2.4.4

https://github.com/StylishThemes/Wikipedia-Dark/commit/4965877f4b2cacb776b4716fe4124e5885029080 fixed this then https://github.com/StylishThemes/Wikipedia-Dark/commit/f9f6c1383953730c9aa66d20595f6e3e961e133a fixed other issues I saw around wikibooks pages and the menu on LaTeX page.

Its likely more stuff will come up, we are always looking for help from our user community,  fixing stuff and restoring colors and other elements, we can always help guiding in right direction.

Thanks again.

**Comment by oowekyala** [comment]
Thanks for fixing it :)
