### ISSUE TITLE
Tool bright table cell backgrounds, too

### ISSUE THREAD

**Issue by UweKeim** [StylishThemes/Wikipedia-Dark#107]
_(Sorry for "spamming" issues here)_

* **Browser**: 

Google Chrome dev 80

* **Operating System**: 

Windows 10, German

* **Link to page with the issue**: 

https://de.wikipedia.org/wiki/Damien_Monier

* **Screenshot**:

![image](https://user-images.githubusercontent.com/415439/70153504-55099280-16af-11ea-9bcf-ae53b1f8a04d.png)

**Comment by the-j0k3r** [comment]
[Click here to upgrade](https://github.com/StylishThemes/Wikipedia-Dark/raw/master/wikipedia-dark.user.css) to v2.4.5

Also fixed borders in reported pages that were broken.
