### ISSUE TITLE
On/Off switch

### ISSUE THREAD

**Issue by felixfoertsch** [StylishThemes/Wikipedia-Dark#11]
Hey guys!

I'm an avid user of your wikipedia dark theme. Thanks for that! I don't know if I'm in the right place for this, but I would like to suggest something: It is really complicated to switch between the light and the dark mode of wikipedia, but sometimes it's necessary. So it would be awesome to have an on/off switch for the theme. E. g. next to the wikipedia logo.

Felix

**Comment by ddavison** [comment]
you could always click the Stylish logo, and uncheck the box next to Wikipedia-Dark :)

**Comment by felixfoertsch** [comment]
Oh, yeah. You are right! I didn't see that, because I don't like having icons in my menu bar. I disable all of them. For me, Stylish is a fire-and-forget extension. It solves a problem and then should not be seen anymore.

I love the simplicity of light switches on site. E.g. RES for reddit does it, or Magic Actions for youtube, too. It's awesome and simple.

If there were such a thing like this, it also could be used for all the other dark themes and provides awesome convenience!

**Comment by Mottie** [comment]
The main issue is that Stylish only allows adding CSS. We can include text, but not HTML, using css content; but really there is no way to include javascript to enable or disable the style.

**Comment by silverwind** [comment]
The only feasible way I see is to package the userstyle into a userscript. I've been meaning to explore this option, but haven't gotten to it yet. I would allow for things like a configuration panel and such a light switch.

**Comment by Poorchop** [comment]
@felixfoertsch I whipped [this userscript](https://github.com/Poorchop/Wikipedia-Dark/blob/userscript/wikipedia-dark.user.js) up quickly just now as a temporary solution until a decision is made about how to approach this. It's obviously pretty basic but it should be easy to modify to your own liking if you want.

**Comment by felixfoertsch** [comment]
Cool, thanks!

Count me in as a supporter for the themes own extensions!

**Comment by Mottie** [comment]
Try this userscript: https://github.com/StylishThemes/Stylish-Toggle

I just made it, but I haven't thoroughly tested it or uploaded it to any site that hosts userscripts like userscripts.org or greasyfork.org.

@silverwind could you check it out and do your magic? :wink:

**Comment by ddavison** [comment]
you're awesome @Mottie

**Comment by silverwind** [comment]
Hmm, doesn't seem to be doing anything for me in Firefox, but I'll check this out more closely later.

**Comment by Mottie** [comment]
Thanks @ddavison!

@silverwind Odd, it works for me in Firefox... I just tested it locally, but I haven't tried to inject it as an official userscript yet.

**Comment by Mottie** [comment]
Oh nevermind, I see the problem. In Chrome, Stylish injects the style into the page whereas in Firefox, the style is added to the background, like it's a shadow DOM style. Hmm, not sure how to get around that then.
