### ISSUE TITLE
Can't read text in edit options

### ISSUE THREAD

**Issue by theslimshaney** [StylishThemes/Wikipedia-Dark#113]
* **Browser**:  Firefox 72
* **Operating System**: Ubuntu 19.10
* **Link to page with the issue**: https://en.wikipedia.org/w/index.php?title=GitHub&action=edit
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/33791263/74095853-791c9200-4aab-11ea-82cc-b2dc78db3625.png)

**Comment by the-j0k3r** [comment]
Thanks for report =) will be fixed shortly.
