### ISSUE TITLE
Text in tooltip box is unreadable 

### ISSUE THREAD

**Issue by DesertStars** [StylishThemes/Wikipedia-Dark#115]
Text in tooltip box that links to references section is unreadable, only happens to plain text, if it links to the anoher url it looks just fine.

* **Browser**: Firefox 73.0.1
* **Operating System**: Ubuntu 18.04
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Wikipedia [Though it happens on every Wikipedia page AFAIK.]
* **Screenshot**:

Theme enabled, text is invisible.
![2020-03-02_16-25-58](https://user-images.githubusercontent.com/53870341/75680583-f601ec80-5ca2-11ea-8318-a932c2e5037d.png)

Selected unreadable text.
![2020-03-02_16-27-56](https://user-images.githubusercontent.com/53870341/75680586-f7331980-5ca2-11ea-8922-a061cda3a62d.png)

Theme disabled, text is readable without any issue.
![2020-03-02_16-28-15](https://user-images.githubusercontent.com/53870341/75680588-f7331980-5ca2-11ea-9c34-ed4871a5a773.png)

**Comment by Mottie** [comment]
Hi @DesertStars!

Thanks for reporting this problem. It should be fixed now, please update the usercss.

**Comment by DesertStars** [comment]
Yeah, it's been fixed. Thanks for the quick fix and also for great looking theme too!

**Comment by the-j0k3r** [comment]
Plenty of re-work went into making it pretty, some 70 hours on my end.

**Comment by the-j0k3r** [comment]
And BTW this isnt fixed by a long shot, what about the rest of these?
