### ISSUE TITLE
White background SVGs unreadable

### ISSUE THREAD

**Issue by jasonkena** [StylishThemes/Wikipedia-Dark#116]
I'm not sure if this is related to https://github.com/StylishThemes/Wikipedia-Dark/issues/93 or https://github.com/StylishThemes/Wikipedia-Dark/issues/22, but I can't seem to find a solution.
* **Browser**:  Firefox 75.0b7
* **Operating System**: OSX Catalina 10.15.3
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Multivariate_normal_distribution
* **Screenshot**:
![Screen Shot 2020-03-25 at 16 46 27](https://user-images.githubusercontent.com/35003073/77523354-31659480-6eb8-11ea-85b7-3dd85e24ce8a.png)

**Comment by the-j0k3r** [comment]
Thanks for report, should be fixed shortly.

**Comment by the-j0k3r** [comment]
please upgrade to 3.1.19
