### ISSUE TITLE
Docs: Add Supported Theme

### ISSUE THREAD

**Issue by srguglielmo** [StylishThemes/Wikipedia-Dark#117]
Hi,

This theme is great! Thank you for working on it!

When I first installed it, I thought it was broken. However I realized I was using a non-default theme in the [Wikipedia preferences](https://en.wikipedia.org/wiki/Special:Preferences#mw-prefsection-rendering). After testing each theme, I realized that Wikipedia-Dark only supports the default `vector` theme. The other themes (`minerva`, `modern`, `monobook`, and `timeless`) are broken in some way (some more than others).

Note this applies to a desktop browser (Firefox 75.0 in my case). I did not test mobile themes.

Might I recommend adding a note about this in `README.md`? Maybe in the `Limitations` section?

**Comment by the-j0k3r** [comment]
Yea we dont support anything but default and supporting all others is impossible, Not even going to try.

But a note shall be added.

thanks for reaching out to us with that. =)
