### ISSUE TITLE
Mozilla Wiki is broken (many ways)

### ISSUE THREAD

**Issue by Grossdm** [StylishThemes/Wikipedia-Dark#120]
The Mozilla Wiki is broken.
I would grab a screenshot, but I've already hacked out the `@-moz` parts that apply this style to it.

* **Browser**: Firefox 75.0 release
* **Operating System**: Microsoft Windows [Version 10.0.18363.815] 64 bit (winver.exe says Version 1909)
* **Link to page with the issue**: [https://wiki.mozilla.org/Main_Page](https://wiki.mozilla.org/Main_Page)
* **Screenshot**: omitted - sorry.

**Comment by the-j0k3r** [comment]
>  I would grab a screenshot, but I've already hacked out the `@-moz` parts that apply this style to it.

Because you have edited the style locally you will need to force update this style, else you wont get the update that fixes this because local edits trump updates.

**Comment by Grossdm** [comment]
Thank you kindly for your response!
I understand that I should have included a screenshot. It looked like this stylesheet had not had any activity for a while - I think that's why I began modifying it before reporting the issue(s).

I will update now. It was thoughtful of you to mention how to force the update.

**Comment by Grossdm** [comment]
> Because you have edited the style locally you will need to force update this style, else you wont get the update that fixes this because local edits trump updates.
> For future reference try to fill n the bugs issue with screenshots, especially if its particular pages, it is easier to know what the issue is, rather than vague statements.
> Fix incoming in a few.

- **Browser**: Firefox 94.0.2
- **Operating System**: Windows 7 Enterprise 64 bit Build 7601, Service Pack 1
- **Link to page with the issue**: https://wiki.mozilla.org/Main_Page
- **Screenshot**: Both with and without the userstyle applied

I had forgotten about opening this issue, when I was again frustrated with the same problem.
Please note that I did force and update last year per your suggestion.

Do you see that the text "Firefox 94.0.2	Released on 2021-11-24
Based on Gecko 94.0" becomes unreadable?

I have added the "Dark Gray Text" and "Dark IMG" userstyles (neither was active for the screenshots, and neither helps).

Please consider either fixing the problem on Mozilla Wiki or not applying the style(s) to that site.

Thanks

- **Browser**: Firefox 94.0.2
- **Operating System**: Windows 7 Enterprise 64 bit Build 7601, Service Pack 1
- **Link to page with the issue**: https://wiki.mozilla.org/Main_Page
- **Screenshot**: Both with and without the userstyle applied

![MozillaWiki-2021-12-02](https://user-images.githubusercontent.com/836787/144512356-4079134b-639c-4e24-bbbd-c903f963f902.jpg)

![MozillaWiki-without-userstyle-2021-12-02](https://user-images.githubusercontent.com/836787/144512306-78822d0e-fbb2-4d09-b224-f727b7ae1bed.jpg)

**Comment by the-j0k3r** [comment]
> Please consider either fixing the problem on Mozilla Wiki or not applying the style(s) to that site.

Please consider contributing fixes instead just because of such a small issue with the text removing the whole site is not any kind of solution.

If it were the case of the whole lot being broken...

In any case, best solution you can do if it SO annoying for you, is exclude the site via Stylus.

![wut](https://user-images.githubusercontent.com/31389848/144627551-03ca0dfb-183a-4cd5-9370-ef053d2ae2e9.gif)
