### ISSUE TITLE
Side links getting weird light color

### ISSUE THREAD

**Issue by REIS0** [StylishThemes/Wikipedia-Dark#122]
This started happening recently, as the screenshot shows it gets this annoying light color in the links and makes them almost unreadable, this screenshot was in the fucsia os page but i could reproduce with all pages i've visited.

* **Browser**: Firefox 76
* **Operating System**:  Pop_OS!
* **Link to page with the issue**:  https://en.wikipedia.org/wiki/Google_Fuchsia
* **Screenshot**:
![image](https://user-images.githubusercontent.com/38042161/81355751-f6619e00-90be-11ea-8a8a-c56c1e09c7a3.png)

**Comment by the-j0k3r** [comment]
This issue was fixed last week, please ensure youre version of Wikipedia Dark is up-to-date currently v3.3.4

Click [here](https://github.com/StylishThemes/Wikipedia-Dark/raw/master/wikipedia-dark.user.css) to force update

**Comment by REIS0** [comment]
It was in the old version, after updating no more problems.

**Comment by the-j0k3r** [comment]
Figured as much, thx for the reply. =)
