### ISSUE TITLE
Side links weird background

### ISSUE THREAD

**Issue by caltaojihun** [StylishThemes/Wikipedia-Dark#124]
Looks like #122. Happens in all pages, and in other languages too. I'm using the latest version (3.3.5)
* **Browser**: Edge Chromium 81. Also Chrome 81
* **Operating System**: Windows 10
* **Link to page with the issue**: [https://en.wikipedia.org/wiki/Main_Page](https://en.wikipedia.org/wiki/Main_Page)
* **Screenshot**: 
![msedge_uLLsrFxke0](https://user-images.githubusercontent.com/54984492/81710387-e4a44000-949c-11ea-885d-fb4fec01a2a4.png)

**Comment by the-j0k3r** [comment]
Seems theres updates filtering though breaking these. Will fix.
