### ISSUE TITLE
Wiktionary unstyled elements

### ISSUE THREAD

**Issue by kfdz277** [StylishThemes/Wikipedia-Dark#126]
* **Browser**: Firefox 76.0.1
* **Operating System**: Windows 10 1909
* **Link to page with the issue**: https://en.wiktionary.org/wiki/魔天 and https://en.wiktionary.org/wiki/Wiktionary:Main_Page
* **Screenshot**: ![image](https://user-images.githubusercontent.com/55974345/82019190-c7b26d00-9654-11ea-8c87-3125086b1689.png) and 
![image](https://user-images.githubusercontent.com/55974345/82019307-fd575600-9654-11ea-875e-fc3fb7b0eb6e.png)

**Comment by the-j0k3r** [comment]
Hello and thx for reaching out.

Problem 1 https://en.wiktionary.org/wiki/魔天

![Screenshot_2020-05-15 魔天 - Wiktionary](https://user-images.githubusercontent.com/31389848/82023567-bede8d00-968e-11ea-8200-c4f35aad581b.png)

As page doesn't exist I cant find the unstyled portions.

The other page https://en.wiktionary.org/wiki/Wiktionary:Main_Page its fixed.

**Comment by the-j0k3r** [comment]
I was able to fix the issue 1 by visiting other similar pages.

fix incoming.

**Comment by kfdz277** [comment]
weird how that link didnt work lol, well thanks

**Comment by the-j0k3r** [comment]
yea its fixed, thanks for feedback. pushing in a few.

**Comment by the-j0k3r** [comment]
Feel free to force update to 3.4.0
