### ISSUE TITLE
Color of visited hyperlinks is very hard to distinguish

### ISSUE THREAD

**Issue by guitarjorge24** [StylishThemes/Wikipedia-Dark#13]
Hi, I'm having the same issue with this skin as with the Stackexchange one. The issue is that the visited hyperlinks look almost identical to regular text. Sorry for nagging about the same thing on a different skin :P

**Comment by Mottie** [comment]
Hi @guitarjorge24!

Ok, I'll look into it.

**Comment by Mottie** [comment]
Ok, I added a visited link color to Wikipedia as well :grin:
