### ISSUE TITLE
Bright menu tabs

### ISSUE THREAD

**Issue by stonecrusher** [StylishThemes/Wikipedia-Dark#132]
* **Browser**: FF77.0.1
* **Operating System**: Win10 1909 
* **Link to page with the issue**: https://de.wikipedia.org/wiki/Hase
* **Screenshot**: 
![wiki dark](https://user-images.githubusercontent.com/1388389/85371117-0da20100-b530-11ea-96d8-a72979397349.PNG)

`.vector-menu-tabs li`
has a CSS
`background-image: linear-gradient(to top,#77c1f6 0,#e8f2f8 1px,#ffffff 100%)`
which makes it bright.

**Comment by the-j0k3r** [comment]
Thans for report, this use to be `div.vectorTabs li.selected` and now is `vector-menu-tabs .selected` as well, seems the background-image is new also.

Anywho, fix incoming. ;)
