### ISSUE TITLE
Colour boxes are not showing their correct colours, only greyscale

### ISSUE THREAD

**Issue by ColonelGerdauf** [StylishThemes/Wikipedia-Dark#134]
Firefox
Windows 10
https://en.wikipedia.org/wiki/Shades_of_purple

![Annotation example](https://user-images.githubusercontent.com/6895655/89195827-51e4e000-d577-11ea-9ed9-da37a3ada8f5.png)

**Comment by the-j0k3r** [comment]
@ColonelGerdauf thanks for report, this is an ongoing battle given the inline HMTL elements are used for everything and their mothers.

Please upgrade to 3.4.9 https://github.com/StylishThemes/Wikipedia-Dark/raw/master/wikipedia-dark.user.css to fix issue
