### ISSUE TITLE
"Current version" has white background

### ISSUE THREAD

**Issue by TotalCaesar659** [StylishThemes/Wikipedia-Dark#136]
* **Browser**: Chromium 83
* **Operating System**: Lubuntu 20.04
* **Link to page with the issue**: https://ru.wikipedia.org/wiki/Команда_года_по_версии_ПФА
* **Screenshot**:
![1](https://user-images.githubusercontent.com/14265316/90035009-fb3f7a80-dcc9-11ea-9057-698fb01b3929.png)

**Comment by the-j0k3r** [comment]
Please update to 3.4.12 should take care of both issues + whatever I found on those links you shared.

**Comment by TotalCaesar659** [comment]
Thanks, both bugs are fixed now.
