### ISSUE TITLE
star button is not black

### ISSUE THREAD

**Issue by wadawada** [StylishThemes/Wikipedia-Dark#138]
* **Browser**: Chrome
* **Operating System**: Windows 10 
* **Link to page with the issue**: 
https://en.wikipedia.org/wiki/Circular_reference
* **Screenshot**:
![star](https://user-images.githubusercontent.com/9424144/90977074-6d4c6680-e4f7-11ea-821e-d83a50d715c9.png)

**Comment by the-j0k3r** [comment]
@wadawada I cant really see this star icon.

![Capture](https://user-images.githubusercontent.com/31389848/90984787-a9271080-e577-11ea-9602-80743188251a.PNG)

Can you please inspect the area and give me the selector for this?

**Comment by Mottie** [comment]
@the-j0k3r you need to be logged in

![](https://user-images.githubusercontent.com/136959/90988658-2b084100-e55a-11ea-8fe2-15f0f954cb42.png)

**Comment by wadawada** [comment]
```
<li id="ca-unwatch" class="icon mw-watchlink"><a href="/w/index.php?title=Circular_reference&amp;action=unwatch" data-mw="interface" title="Remove this page from your watchlist [alt-shift-w]" accesskey="w" deluminate_imagetype="unknown">Unwatch</a></li>

.vector-menu-tabs li, .client-js #preftoc li {
    border-right: 1px solid var(--gray-5) !important;
}
```

could be
`ul li a {  background-color: #000000}`

**Comment by the-j0k3r** [comment]
> @the-j0k3r you need to be logged in

I dont have or want accounts just for the hell of it. This being  the hell of it =)

Thanks though, I think I have a cleaner solution to prevent these from showing up ever again.

**Comment by the-j0k3r** [comment]
https://github.com/StylishThemes/Wikipedia-Dark/commit/49c30dc54935c7441d33b807d31c8d4c6fc62899 should be more resilient and far reaching.

Please upgrade to 3.4.14
