### ISSUE TITLE
Stylesheet broken on French wikipedia

### ISSUE THREAD

**Issue by oowekyala** [StylishThemes/Wikipedia-Dark#139]
French wikipedia pages show a weird mix of dark and light elements. Other languages look fine

* **Browser**: Firefox 79.0
* **Operating System**: Ubuntu 16.04
* **Link to page with the issue**: https://fr.wikipedia.org/wiki/Information (any page on fr.wikipedia.org I've seen) 
* **Screenshot**:

![Capture d’écran de 2020-08-26 04-06-21](https://user-images.githubusercontent.com/24524930/91247083-bf88c400-e751-11ea-96eb-a89dcb7317ae.png)

**Comment by the-j0k3r** [comment]
It is indeed a mess, they have updated their vector style css for one.

Fix incoming, need to take care of a couple of things first. 

Thx for report.

**Comment by the-j0k3r** [comment]
Should be fixed by https://github.com/StylishThemes/Wikipedia-Dark/commit/4b8ec17f08f7373055396c3a243c805453b03f60#diff-c6b76bebc6d6643519e4e68ac9aa438aL5080-R5429

please upgrade to v3.4.15

**Comment by oowekyala** [comment]
Great, thanks for the fix!
