### ISSUE TITLE
translation page not in black

### ISSUE THREAD

**Issue by wadawada** [StylishThemes/Wikipedia-Dark#141]
* **Browser**: 
chrome 85.0.4183.83
* **Operating System**:
windows 10 
* **Link to page with the issue**: 
https://zh.wikipedia.org/w/index.php?title=Special:%E5%86%85%E5%AE%B9%E7%BF%BB%E8%AF%91&page=EMF+measurement&from=en&to=zh&targettitle=&campaign=interlanguagelink
* **Screenshot**:
![image](https://user-images.githubusercontent.com/9424144/92464014-640efb00-f181-11ea-855e-bbb1915d771d.png)

**Comment by the-j0k3r** [comment]
@AfroThundr3007730 any chance you can look into this?

**Comment by AfroThundr3007730** [comment]
Hmm, this is gonna be fun. That's a whole 'nother interface, mostly based on OOUI, but still... When I have some spare time I can work on this.

**Comment by AfroThundr3007730** [comment]
Sorry for the long delay, been pretty busy with work and other shenanigans. Should be fixed now. Let me know if anything was missed.
