### ISSUE TITLE
settings not in black

### ISSUE THREAD

**Issue by wadawada** [StylishThemes/Wikipedia-Dark#142]
* **Browser**: 
chrome 85.0.4183.83
* **Operating System**:
windows 10 
* **Link to page with the issue**: 
https://en.wikipedia.org/wiki/Special:Preferences#mw-prefsection-rendering
https://en.wikipedia.org/wiki/Special:Preferences#mw-prefsection-echo
* **Screenshot**:
![image](https://user-images.githubusercontent.com/9424144/92678073-04783300-f2da-11ea-9067-b5f8c939e17f.png)
![image](https://user-images.githubusercontent.com/9424144/92678147-2c679680-f2da-11ea-8491-fd1a702251f9.png)

**Comment by the-j0k3r** [comment]
Forewarning: Apologies, this requires an account to login, at this time I personally dont have one and will have to consider this slippery slope given the style supports wikis of all kinds and countries and languages. Not all fixes to one wiki apply across all so if I have one account to fix something in any given wiki, how many accounts will this end up being? (I dont actually edit or contribute to any wiki so less interesting prospect for me).

As such instead, Ill ask for your help, please provide copy and paste of the of the broken elements while the devtools inspector is open over these.

Please copy and paste the html on the inpector for parts that have inline styles, and for the classes on the right side copy the respective rule.

If you paste those here I will be able to do a blind fix.

Please provide info for all the affected areas, Im looking for normal class, hovered/active/focus for all color properties on the affected areas.

Sorry for the inconvenience.

Alternatively PRs are also welcome.

**Comment by the-j0k3r** [comment]
Forewarning: Apologies, this requires an account to login, at this time I personally dont have one and will have to consider this slippery slope given the style supports wikis of all kinds and countries and languages. Not all fixes to one wiki apply across all so if I have one account to fix something in any given wiki, how many accounts will this end up being? (I dont actually edit or contribute to any wiki so less interesting prospect for me).

As such instead, Ill ask for your help, please provide copy and paste of the of the broken elements while the devtools inspector is open over these.

Please copy and paste the html on the inpector for parts that have inline styles, and for the classes on the right side copy the respective rule.

If you paste those here I will be able to do a blind fix.

Please provide info for all the affected areas, Im looking for normal class, hovered/active/focus for all color properties on the affected areas.

Sorry for the inconvenience.

Alternatively PRs are also welcome.

Thanks in advance.

**Comment by AfroThundr3007730** [comment]
There's still an annoying FOUC on the `oo-ui-dropdownWidget` elements while the page JS loads, but I can't capture it in the debugger, so it can stay for now.
