### ISSUE TITLE
Bullet points inside of a pop-up are white and un-readable.

### ISSUE THREAD

**Issue by gubareve** [StylishThemes/Wikipedia-Dark#147]
Bullet points inside of a pop-up are white and un-readable. Forgive me if I got the terminology wrong, I don't know the syntax for wikipedia.
* **Browser**: 
Firefox
* **Operating System**:
w10 
* **Link to page with the issue**: 
https://en.wikipedia.org/wiki/Lymphoma
* **Screenshot**:
![](https://cdn.evang.dev/032ZltQ.png)

**Comment by the-j0k3r** [comment]
Thx, added to todo list.

Bare with me.

**Comment by the-j0k3r** [comment]
The actual issue is that the whole section is unstyled, the bullet point color is fine.
