### ISSUE TITLE
Music album charts table has white background

### ISSUE THREAD

**Issue by d-Rickyy-b** [StylishThemes/Wikipedia-Dark#148]
Best dark theme for Wikipedia so far! Thank you!

The issue is pretty self explanatory - the background for the music album table on the right sidebar got white backgrounds.

* **Browser**: Firefox 81.0.2 (64-Bit)
* **Operating System**: Windows 10
* **Link to page with the issue**: https://de.wikipedia.org/wiki/Weird_Al_Yankovic
* **Screenshot**:

![grafik](https://user-images.githubusercontent.com/5798157/96199880-cdd8ac80-0f58-11eb-868d-64d42c5c5cfd.png)

![grafik](https://user-images.githubusercontent.com/5798157/96199923-eea10200-0f58-11eb-92d8-ec91a669a031.png)

**Comment by the-j0k3r** [comment]
Thx for report will get to it soon.
