### ISSUE TITLE
Broken French wiktionary

### ISSUE THREAD

**Issue by KarlitosVII** [StylishThemes/Wikipedia-Dark#149]
Hello,
Like #140, french version of wiktionary is broken.
Thanks in advance. :)

* **Browser**: Firefox Developer 83
* **Operating System**: Windows 10 2004
* **Link to page with the issue**: https://fr.wiktionary.org, https://fr.wiktionary.org/wiki/schmilblick
* **Screenshot**:
![Sans titre](https://user-images.githubusercontent.com/7722685/97113721-8981a500-16ec-11eb-9398-ccecf588856b.png)

**Comment by the-j0k3r** [comment]
Thanks, Ill fix it this time, but will no longer maintain this style until further notice due to real live.

Maintainers wanted.
