### ISSUE TITLE
White background

### ISSUE THREAD

**Issue by UweKeim** [StylishThemes/Wikipedia-Dark#150]
* **Browser**: 

Google Chrome 

* **Operating System**: 

Windows 10

* **Link to page with the issue**: 

https://fr.wikipedia.org/wiki/Liste_des_%C3%A9pisodes_de_Profilage#%C3%89pisode_6_:_De_chair_et_d'os

* **Screenshot**:

![image](https://user-images.githubusercontent.com/415439/97289530-98309f00-1847-11eb-85b3-a108adc6723e.png)

**Comment by the-j0k3r** [comment]
Thanks for report, maintenance of opensource repos is low on my priority list at this time,

Contributions are always welcome in the meanwhile.
