### ISSUE TITLE
Table cell has white background

### ISSUE THREAD

**Issue by TotalCaesar659** [StylishThemes/Wikipedia-Dark#153]
* **Browser**: Chromium 84.0.4147.135
* **Operating System**: Ubuntu 20.04.1
* **Link to page with the issue**: https://en.wikipedia.org/wiki/List_of_Australian_Open_men%27s_singles_champions
* **Screenshot**:

![1](https://user-images.githubusercontent.com/14265316/100387941-55c2d380-303a-11eb-8705-d84bc1779260.png)

**Comment by yukulele** [comment]
This fix doesn't work with `bgcolor` 

exemple: the [same table](https://en.wikipedia.org/wiki/List_of_Australian_Open_men%27s_singles_champions#Australasian_Championships) in 1986
