### ISSUE TITLE
It doesn't fully work for Persian (Farsi) Wikipedia

### ISSUE THREAD

**Issue by sheikhijat** [StylishThemes/Wikipedia-Dark#159]
* **Firefox**: 
* **Windows 10**: 
* **https://fa.wikipedia.org/wiki/%D8%B9%D8%A7%D8%AF%D9%84_%D9%81%D8%B1%D8%AF%D9%88%D8%B3%DB%8C%E2%80%8C%D9%BE%D9%88%D8%B1**: 
* **![Screenshot_2021-01-24 عادل فردوسی‌پور - ویکی‌پدیا، دانشنامهٔ آزاد](https://user-images.githubusercontent.com/72881613/105633638-fe40b880-5e6e-11eb-9017-655bf8f89cab.png)**:

**Comment by Mottie** [comment]
Hi @sheikhijat!

Thanks for reporting this problem. I'll get it fixed ASAP!

**Comment by sheikhijat** [comment]
> 
> 
> Hi @sheikhijat!
> 
> Thanks for reporting this problem. I'll get it fixed ASAP!

Thanks! That's much appreciated. 👍🏻
