### ISSUE TITLE
Wikipedias result board for racing records looks pretty horrible

### ISSUE THREAD

**Issue by JesperVa** [StylishThemes/Wikipedia-Dark#167]
* **Browser**: Chrome
* **Operating System**: Windows 
* **Link to page with the issue**:  https://en.wikipedia.org/wiki/2020_Formula_One_World_Championship#World_Drivers'_Championship_standings
* **Screenshot**: https://i.imgur.com/lovTtRA.png

Pretty hard to see the any of the standings and the default colours are not very dark-mode friendly.

**Comment by the-j0k3r** [comment]
These are inline styles, we cant cover 100% of all cases, see https://github.com/StylishThemes/Wikipedia-Dark#limitations

It can be fixed so PR welcome.

**Comment by JesperVa** [comment]
My bad just copied the issue link in the style, I'll see if I can have a look at this issue and see if these can be improved.

Might push up a PR in a few days.
