### ISSUE TITLE
Notification icons hard to read

### ISSUE THREAD

**Issue by nyuszika7h** [StylishThemes/Wikipedia-Dark#17]
The notification icons are black on a dark background and hard to read. (And also the Wikipedia logo, but that's a smaller issue.) Oh, and the Alerts/Notices headers have the default bright background while they are loading.

# Screenshots

![Screenshot of notification icons](https://u.nya.is/nlaimu.png)

----

![Screenshot of "Notices" menu while loading (bright background header)](https://u.nya.is/fufxeu.png)

----

![Screenshot of "Notices"menu when loaded (dark background header)](https://u.nya.is/lymddq.png)

**Comment by Mottie** [comment]
Hi @nyuszika7h!

I can fix the icon and notice loading background no problem. The Wikipedia logo text is part of the logo, so we either invert the entire thing (the logo looks funky) or leave it as is...
