### ISSUE TITLE
Overrides background-colored table header foreground colors making text hard to read

### ISSUE THREAD

**Issue by nyuszika7h** [StylishThemes/Wikipedia-Dark#18]
The style forces table headers' foreground color to be white, even the background color is different and white is unreadable on it, such as this yellow (from the _The Thundermans_ article):

![Screenshot](https://u.nya.is/hamrxf.png)

**Comment by Mottie** [comment]
Hi @nyuszika7h!

Yeah, I need to remove the global selector... I've replaced it with individual elements so I might have missed something! Please let me know!
