### ISSUE TITLE
Colour boxes are not showing where intended

### ISSUE THREAD

**Issue by ColonelGerdauf** [StylishThemes/Wikipedia-Dark#181]
* **Browser**: Firefox
* **Operating System**: Windows 10
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Red or any other page about colours
* **Screenshot**:
What it should have looked like ideally:
![ideal](https://user-images.githubusercontent.com/6895655/120258746-9e18b380-c260-11eb-8c5e-691f8d267390.png)

And what it looks like under the current code:
![bugged](https://user-images.githubusercontent.com/6895655/120258821-ba1c5500-c260-11eb-9919-4efca27252bb.png)

**Comment by ColonelGerdauf** [comment]
I should repeat from my pull request that the code block responsible for causing this discrepancy is a disorganized mess, making it impossible for me to figure out a way to work out this issue without removing the part of code altogether.

**Comment by the-j0k3r** [comment]
Easy fix add `:not([style*="000"])` to the .infobox line, should clear up most of these if not all.

@AfroThundr3007730
