### ISSUE TITLE
Mathematical notation has black text

### ISSUE THREAD

**Issue by awebeer256** [StylishThemes/Wikipedia-Dark#184]
* **Browser**: Firefox
* **Operating System**: Linux Mint
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Speed_of_sound#Equations
* **Screenshot**: ![image](https://user-images.githubusercontent.com/26385859/120376155-833e5180-c2e9-11eb-8bd0-dbf640e2d79b.png)

The culprit is on line 3953:
```
img.mwe-math-fallback-image-inline, /* snip */ {
  filter: invert(1) brightness(90%);
}
```
Removing this rule fixes it:
![image](https://user-images.githubusercontent.com/26385859/120376667-255e3980-c2ea-11eb-8eff-2ed218bef284.png)
But that prompts the question: why was that rule created in the first place? Was there a recent change on Wikipedia's backend such that these dynamically generated images are now very light gray instead of very dark? If I disable the userstyle entirely, this stuff is light gray on white, and therefore _still_ nearly invisible!
![image](https://user-images.githubusercontent.com/26385859/120379034-2d6ba880-c2ed-11eb-9b48-376f44ed68ab.png)

**Comment by the-j0k3r** [comment]
Its working pretty well as is...

![Screenshot 2021-06-02 at 13-40-57 Speed of sound - Wikipedia](https://user-images.githubusercontent.com/31389848/120474195-33728f80-c3a8-11eb-8619-a37013c992f5.png)

Make sure you are using the latest version of style.

**Comment by the-j0k3r** [comment]
Its working pretty well as is... Removing that rule breaks it, so the issue is on your side only.

Make sure you are using the latest version of style @ 3.5.5

proof

![Screenshot 2021-06-02 at 13-40-57 Speed of sound - Wikipedia](https://user-images.githubusercontent.com/31389848/120474195-33728f80-c3a8-11eb-8619-a37013c992f5.png)

**Comment by awebeer256** [comment]
Sorry for the 2.5-year vanishing act. :face_with_spiral_eyes: 

This depends on the default text colour in your browser settings. Equations will always display as the result of that colour sent through the filter I mentioned before: inverted and then reduced brightness by 10%. My colour settings look like this:
![image](https://github.com/StylishThemes/Wikipedia-Dark/assets/26385859/3202070c-37f0-4a0e-9389-6b3336919cdd)
…so equations display as dark grey. If my text colour is set to dark red, they display as cyan.
![image](https://github.com/StylishThemes/Wikipedia-Dark/assets/26385859/32eabfe9-a55b-4c82-89cb-234d1384c09f)
![image](https://github.com/StylishThemes/Wikipedia-Dark/assets/26385859/6ada44f2-b80d-489f-9d2c-d4c254f311db)
Since this is a dark mode theme, being hostile to users who have set their default colours to dark mode colours seems pretty unacceptable to me.
