### ISSUE TITLE
Wiki logo

### ISSUE THREAD

**Issue by o-r-i-z-u-r-u** [StylishThemes/Wikipedia-Dark#188]
Hi I'm new to github and I signed up specifically so I could make this request

Would it be possible to edit the style of the [Wikipedia logo](https://user-images.githubusercontent.com/88693606/128819760-4612a460-2df6-4131-bba7-4bc0283e48fb.png)
 (wordmark and tagline) on the main page so that it is visible using Wikipedia Dark?
 
Thanks for reading, the source elements are as follows:

[Wordmark SVG](https://en.wikipedia.org/static/images/mobile/copyright/wikipedia-wordmark-en.svg)
`<img class="mw-logo-wordmark" alt="Wikipedia" src="/static/images/mobile/copyright/wikipedia-wordmark-en.svg" width="119" height="18">`

[Tagline SVG](https://en.wikipedia.org/static/images/mobile/copyright/wikipedia-tagline-en.svg)
`<img class="mw-logo-tagline" alt="The Free Encyclopedia" src="/static/images/mobile/copyright/wikipedia-tagline-en.svg" width="117" height="13">`

**Comment by AfroThundr3007730** [comment]
Those appear to show up fine when I checked a minute ago. Are you using mobile view, or a MediaWiki skin other than the default Vector skin?

**Comment by o-r-i-z-u-r-u** [comment]
Hmm nope, I'm browsing regular ol' https://en.wikipedia.org/ 
as in [this screenshot](https://user-images.githubusercontent.com/88693606/128819760-4612a460-2df6-4131-bba7-4bc0283e48fb.png)
Wikipedia Dark 3.5.8 and default vector skin
I wonder what is making the difference?

**Comment by the-j0k3r** [comment]
> Hmm nope, I'm browsing regular ol' https://en.wikipedia.org/

You are using a mobile device browser, because Ive just tested it and it confirms your issue.

This is also obvious because your source images are from mobile view.

Anyway. ill push a fix if @AfroThundr3007730 makes a release.

**Comment by o-r-i-z-u-r-u** [comment]
It's not a mobile device browser. I had another look and it's browsing in non-legacy Vector mode. This is available for users on the site (possibly as the default, I can't recall)
It just happens that they store the SVGs in a mobile directory. Otherwise, if you're not logged in, it displays 
the logo as a [PNG ](https://en.wikipedia.org/static/images/project-logos/enwiki.png) using the legacy style

**Comment by the-j0k3r** [comment]
I tested with a mobile UA and regular desktop UA, not logged in as I dont care about that functionality and by extension not using any settings for the site, this implies default from my side.

Issue <s>was</s> duplicated with mobile UA.

The CSS used doesnt care about file extensions.

So wait until update goes trough when @AfroThundr3007730 has time to make a release with the fix.

Youre welcome to test the fix if it works for you but rememebr any locally edits to any style trumps styles autoupdates, so youll need to force update manually if you test the fix.

All Im interested now is if it worked or not, my guess is it fixed your issue.
