### ISSUE TITLE
Langage selector design issue

### ISSUE THREAD

**Issue by nouhmaster** [StylishThemes/Wikipedia-Dark#194]
#  Presentation

Hi we are a students in computer science in  a Paris University 

## Description

1. We see a bug when you want to change a language. Here a screenshot:

![capture](https://user-images.githubusercontent.com/47368896/152769468-20a25dd1-8a93-4bd0-98e0-cf19c0f9d21d.png)

## Contribution

We would try to correct this bug, if you are OK.

**Comment by the-j0k3r** [comment]
Thanks for report and reaching out to us.

"We" are OK with PR's that follow the styling of not just shadows of gray.but the dark counterparts of colors using existing rules where possible. However Anything that addresses the bugs would be welcome.

**Comment by nouhmaster** [comment]
Hello

Sorry , we made a mistake ,we choose the wrong extension.
