### ISSUE TITLE
#bodycontent pre has no color defined and appears black

### ISSUE THREAD

**Issue by Fdrph** [StylishThemes/Wikipedia-Dark#20]
**line 83**

_add color :_

  #bodyContent pre, #bodyContent code, span.plainlinks * {
      background-color: #111 !important;
      ->color: #b9b9b9;
  }

example: https://en.wikipedia.org/wiki/Single-precision_floating-point_format
notice the content boxes

**Comment by Mottie** [comment]
Hi @Fdrph!

Thanks for letting me know! I'll have it fixed here shortly.
