### ISSUE TITLE
Major UI update

### ISSUE THREAD

**Issue by ColonelGerdauf** [StylishThemes/Wikipedia-Dark#200]
Wikimedia Foundation chose to update the UI of WIkipedia very recently. I personally appreciate the increased ease of use of the site now.

Most things for the theme still work, but the table of contents, moved to the side in sticky CSS position, is now unaffected by this theme. Also, the the design changes have made the main logo banner hard to read as it is in black.

**Comment by ibillingsley** [comment]
The top bar is still white when you scroll down:
![Screenshot 2023-02-11 142515](https://user-images.githubusercontent.com/1782216/218277357-1ac1da83-5c62-47d2-80e1-f07e5805b7c0.jpg)

Need to override the background color on `.vector-sticky-header`
