### ISSUE TITLE
Wikidata: Preferred/Deprecated colors are not styled

### ISSUE THREAD

**Issue by tomodachi94** [StylishThemes/Wikipedia-Dark#202]
The "Preferred" rank indicator is a bright green, which doesn't appear to be styled. I'm assuming the same is for the Deprecated rank.

* **Browser**: Vivaldi
* **Operating System**: Linux Mint
* **Link to page with the issue**: https://www.wikidata.org/wiki/Q116308313#P277
* **Screenshot**:
![The "Preferred" rank indicator is a bright green, which doesn't appear to be styled.](https://user-images.githubusercontent.com/68489118/213977422-510f9b96-04ad-4213-939a-1b351e57d0fa.jpeg)

**Comment by AfroThundr3007730** [comment]
Fixed by #206
