### ISSUE TITLE
Background image set to "None" no longer works on the new layout

### ISSUE THREAD

**Issue by DumbIdiot** [StylishThemes/Wikipedia-Dark#207]
If Background image is set to None the background turns white. The old layout that some languages still use works fine, but those that use the updated layout such as English stopped working.

* **Browser**: Chrome
* **Operating System**: Windows 10 64-bit
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Wikipedia
* **Screenshot**: 
![Screenshot 2023-04-27 221159](https://user-images.githubusercontent.com/4354676/234980228-e6ece8e0-7a23-427a-bbbd-b1697b958350.png)

**Comment by AfroThundr3007730** [comment]
Fixed in #206
