### ISSUE TITLE
Wikipedia color changes, not update

### ISSUE THREAD

**Issue by ShaneBeee** [StylishThemes/Wikipedia-Dark#209]
I noticed a little while back, that the sidebar on wikipedia changed, thus the colours are not updated.
Same thing with the header bar

* **Browser**: Safara (using Cascadea extension)
* **Operating System**: macOS 13.3.1
* **Link to page with the issue**: any page really, but example https://en.wikipedia.org/wiki/Minecraft
* **Screenshot**: 
<img width="1422" alt="Screenshot 2023-05-30 at 12 31 31 PM" src="https://github.com/StylishThemes/Wikipedia-Dark/assets/20008482/85f2fd96-4bf5-416d-b236-51e517152111">

**Comment by AfroThundr3007730** [comment]
Fixed in #206
