### ISSUE TITLE
Formulars are unreadable

### ISSUE THREAD

**Issue by aiomaster** [StylishThemes/Wikipedia-Dark#22]
Hi,

I had the problem, that all formulars are unreadable using this dark theme, cause per default wikipedia uses an svg image with grey font color to display that.

Following this advice:
https://www.mediawiki.org/wiki/Extension:Math/advancedSettings#CSS_for_the_MathML_with_SVG_fallback_mode
I could make use of the MathML rendering of firefox, so the right color is used and all formulars are visible.
I thought that this could be usefull for all users of this dark theme, so maybe you want to include it?

Thanks!

**Comment by Mottie** [comment]
Hi @aiomaster!

Currently all math formula images are inverted ([example](https://en.wikipedia.org/wiki/Analysis_of_variance#Logic_of_ANOVA)). 

![2017-01-13 07_38_04-analysis of variance - wikipedia](https://cloud.githubusercontent.com/assets/136959/21931870/6a58ae6e-d963-11e6-90a5-ff5b4ae6ef0e.png)

Would you please share an example page where the formulas are unreadable?

I tried using the css provided on the page you shared, and the result was the raw latex source.

![2017-01-13 07_38_44-analysis of variance - wikipedia](https://cloud.githubusercontent.com/assets/136959/21931884/7611c952-d963-11e6-8c76-0b16e16eaa66.png)

**Comment by aiomaster** [comment]
The same example looks like that for me:

![formulars](https://cloud.githubusercontent.com/assets/220197/21942666/43c4a8b4-d9ce-11e6-9bde-270a37f35cf9.png)

after the proposed css fixes it looks like this for me:

![formulars_mathml](https://cloud.githubusercontent.com/assets/220197/21942764/a162ad18-d9ce-11e6-870a-f7ac251dbcc7.png)

don't know why, but I wondered that this problem didn't appeared for someone else than me.
I should say, that I use a darktheme for my OS. Maybe this does some stuff with the font colors.

**Comment by Mottie** [comment]
Odd indeed... please make sure you're using the most up-to-date dark theme. It is currently v1.0.21, updated last week.

**Comment by moshpirit** [comment]
[I think not all formulas are working this way](https://es.wikipedia.org/wiki/Determinante_(matem%C3%A1tica)#M.C3.A9todos_de_c.C3.A1lculo) I see a huge white rectangle instead of the formula. 

PS: how can I make the letters a bit lighter?

**Comment by moshpirit** [comment]
[The entire page is full of this blank spaces](https://es.wikipedia.org/wiki/Determinante_(matem%C3%A1tica)#Menores_de_una_matriz)

**Comment by Mottie** [comment]
Thanks @moshpirit!

It should be all fixed now.

**Comment by moshpirit** [comment]
It is!! Thank you so much for your support! :)

**Comment by moshpirit** [comment]
Oh, also [here]() "donde /formula es el gradiente evaluado en" appears in black instead of white :-)

**Comment by Mottie** [comment]
@moshpirit Please share the link again.

**Comment by moshpirit** [comment]
Sorry! [here it is](https://es.wikipedia.org/wiki/Gradiente#Aproximaci.C3.B3n_lineal_de_una_funci.C3.B3n) (I also edited the comment)

**Comment by Mottie** [comment]
It looks fine to me.

![](https://user-images.githubusercontent.com/136959/29750073-1a41fc2a-8aff-11e7-921e-7773e106b49d.png)

Please make sure you've installed the most up-to-date userstyle.

**Comment by moshpirit** [comment]
You're right!! my bad, sorry!
