### ISSUE TITLE
"Main article" section no longer targeted by style

### ISSUE THREAD

**Issue by MMachado05** [StylishThemes/Wikipedia-Dark#222]
* **Browser**: Firefox 126
* **Operating System**: Kubuntu 22.04.3
* **Link to page with the issue**: https://en.wikipedia.org/wiki/Tak_and_the_Power_of_Juju#TV_series
* **Screenshot**: 
![image](https://github.com/StylishThemes/Wikipedia-Dark/assets/111894108/fa380d9a-091e-4999-a335-34392da371f6)

**Comment by AfroThundr3007730** [comment]
Currently can't reproduce this. Are you still having this issue?
![image](https://github.com/user-attachments/assets/d5149f41-46ba-4fa0-abe8-8b4a9a356187)

**Comment by MMachado05** [comment]
No I am not! Must have been fixed in the last few months. Thank you!
