### ISSUE TITLE
edit box/WikEd backgrounds

### ISSUE THREAD

**Issue by CaptainFrosty** [StylishThemes/Wikipedia-Dark#24]
I added the following CSS to make the background white when editing wikitext (it's hard to use WikEd with a gray background)

![ss](https://cloud.githubusercontent.com/assets/8523498/22039286/adbc5af4-dccc-11e6-8926-1cedb44bddc3.png)
```
.mw-editfont-monospace {background: #ffffff !important;}
 
div#wikEdFrameInner {background: #ffffff !important;}
```

**Comment by Mottie** [comment]
Hi @CaptainFrosty!

Thanks for letting us know! It'll be fixed in a few minutes.

**Comment by Mottie** [comment]
It looks okay to me... where is the issue? I don't use that editor so I'm not sure where to look.

![2017-01-18 12_11_25-editing game of thrones season 1 - wikipedia](https://cloud.githubusercontent.com/assets/136959/22076826/5b72f27a-dd77-11e6-9757-7ee738107781.png)
