### ISSUE TITLE
Mobile editing background

### ISSUE THREAD

**Issue by CaptainFrosty** [StylishThemes/Wikipedia-Dark#25]
If the edit box for the mobile site could be returned to white or a light background (or lighten the font) that would be great.

![screenshot_2017-01-28-21-04-22](https://cloud.githubusercontent.com/assets/8523498/22401358/c4a3c5fc-e59d-11e6-9d30-28a4acfdd0e3.png)

**Comment by Mottie** [comment]
Hi @CaptainFrosty!

Thanks for reporting the problem! Would you please share a css selector that would correct the problem? It also looks like the header needs a solid background.

**Comment by CaptainFrosty** [comment]
Looks like changing the font to white would be best to keep it dark.

`textarea#wikitext-editor.wikitext-editor {color:#ffffff !important}`

I'm not sure what to do about the header.

**Comment by CaptainFrosty** [comment]
It seems the header is broken up into several HTML elements and I'm having trouble figuring out how to disable transparency on the entire thing. The best fix is probably to have the font light gray on the editor body and the header, and just keep the header background dark with no transparency. I'm just having trouble with accomplishing that because the CSS for the header is complicated.

**Comment by AfroThundr3007730** [comment]
Well, this is (kind of?) not a problem anymore, since the style is currently disabled for mobile pages (see 8271778) pending a style rewrite for the Minerva skin and the other alternates (see #72).

**Comment by the-j0k3r** [comment]
Lets just close this in favor of #72 since mobile is now ignored.
