### ISSUE TITLE
Image description losing color descriptions

### ISSUE THREAD

**Issue by fathermocker** [StylishThemes/Wikipedia-Dark#26]
You can't see the color squares that describe the map in this example:

![image](https://user-images.githubusercontent.com/421528/29594412-1f6c4c58-8787-11e7-945d-4d6b42596a36.png)
![image](https://user-images.githubusercontent.com/421528/29594425-2d4f1710-8787-11e7-9253-4156a1067d64.png)

https://en.wikipedia.org/wiki/Abortion_law#/media/File:Abortion_Laws.svg

**Comment by Mottie** [comment]
Hi @fathermocker!

Thanks for reporting the problem! It's been all fixed.

**Comment by fathermocker** [comment]
Gee thanks for the quickness! @Mottie
