### ISSUE TITLE
White gradient at the end of the preview's text  [having the "Page previews" wikipedia beta feature enabled]

### ISSUE THREAD

**Issue by darkred** [StylishThemes/Wikipedia-Dark#27]
It's about the 'Page previews' beta feature of wikipedia (login to your wikipedia account|[Preferences|'Beta features](https://en.wikipedia.org/wiki/Special:Preferences#mw-prefsection-betafeatures) and enable 'Page previews').

When hovering on a link, there's a white gradient at the end of the preview's text.
Example link: https://en.wikipedia.org/wiki/Jeff_Loomis
Screenshot:
![2017-08-28_015439](https://user-images.githubusercontent.com/723651/29754734-2247da62-8b94-11e7-8480-3ffaabf5ba30.jpg)

PS. Yes, it's a beta feature, but I believe it's super useful to have it enabled,

**Comment by Mottie** [comment]
Hi @darkred!

I'm not seeing the gradient background... I think it was fixed in 1.0.25, please make sure you have that version installed.

**Comment by darkred** [comment]
Yes, that's the version I have

I don't know it helps, but I use Firefox 55.0.2, Stylish 2.0.7, have all the wikipedia beta features enabled, and no other style or script running.

**Comment by Mottie** [comment]
I tried both Stylish 2.0.7 and Stylus 1.1.3.1 with v1.0.25 Wikipedia-Dark style. The preview is narrower, but there's not gradient.

![2017-08-27 17_45_33-jeff loomis - wikipedia](https://user-images.githubusercontent.com/136959/29754685-fb76743c-8b4f-11e7-9811-1327bbf51c47.png)
![2017-08-27 17_45_53-jeff loomis - wikipedia](https://user-images.githubusercontent.com/136959/29754684-f7b9d6f4-8b4f-11e7-9595-682422d8c183.png)

Can you share the HTML?

**Comment by darkred** [comment]
Yes, here is the saved page:
[test page.zip](https://github.com/StylishThemes/Wikipedia-Dark/files/1254769/test.page.zip)

**Comment by Mottie** [comment]
Sorry that doesn't help, the preview is loaded dynamically on hover. Right click inside the preview and copy/paste the HTML into a code block here please... and if you can find the offending css style and share it, that'd be an even better.

**Comment by darkred** [comment]
Unfortunately, setting the link node's `hover` pseudoclass to active doesn't make the popup appear
so I can't seem to examine it in Firefox or Chrome's Inspector.
(I guess I have to put a breakpoint to a related javascript file so to break when a preview popup appears, I tried but couldn't find such ). 

Also, the issue also occurs in Chrome 60 with Stylish 1.8.2.


And, I've installed the style from [the userstyles.org page](https://userstyles.org/styles/105844/wikipedia-dark-st).
I've noticed that there are some differences in version in GitHub in the `html, body` rule:
![2017-08-28_024848](https://user-images.githubusercontent.com/723651/29755136-b41b2208-8b9b-11e7-894a-10fb6ae47481.jpg)
so I tried (in Firefox's Stylish) replacing my installed version with [that from GitHub](https://github.com/StylishThemes/Wikipedia-Dark/raw/master/wikipedia-dark.css)
but the issue remains.

**Comment by Mottie** [comment]
All placehoders (like `/*[[base-color]]*/`) are replaced in the installed style by user preferences:

![](https://user-images.githubusercontent.com/136959/29755375-9793f3c4-8b5c-11e7-9867-9f69773eddc1.png)

I'm going to go ahead and find and disable all bright `box-shadow` definitions that I find in their style and let's see if that fixes this issue.

**Comment by darkred** [comment]
Unfortunately your last commit didn't fix the issue.

<br>

Here is the HTML you asked (it's the `::after` node as seen in the [screenshot ](https://user-images.githubusercontent.com/723651/29780154-62156b9e-8c1d-11e7-900d-7d07dcef57ee.jpg))
_(I navigated via keyboard while hovering link with mouse)_
```
<div class="mwe-popups mwe-popups-fade-in-up flipped_x mwe-popups-image-tri mwe-popups-is-not-tall" role="tooltip" aria-hidden="" style="top: 210px; left: 827px; display: block;">
  <div class="mwe-popups-container">
    <a href="https://en.wikipedia.org/wiki/Nevermore" class="mwe-popups-discreet"><svg xmlns="http://www.w3.org/2000/svg" width="303" height="200"><image xlink:href="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Nevermore_Summerbreeze2007_04.jpg/300px-Nevermore_Summerbreeze2007_04.jpg" x="0" y="-12.5" width="300" height="225" clip-path="url(#mwe-popups-mask-flip)"></image></svg></a>
    <a dir="ltr" class="mwe-popups-extract" href="https://en.wikipedia.org/wiki/Nevermore" lang="en"><b>Nevermore</b> is an American progressive metal band from Seattle, Washington, United States. Formed in 1991, they are known to incorporate elements from various styles such as power metal, modern hard rock, classic heavy metal and technical thrash metal. The band has been on hiatus since 2011, due to personal issues between the band members. In April 2015, lead singer Warrel Dane confirmed that Nevermore has not disbanded, and there is a possibility for them to continue in the next two years with another album.

</a>
    <footer>
      <a class="mwe-popups-settings-icon mw-ui-icon mw-ui-icon-element mw-ui-icon-popups-settings" href="/wiki/Special:Preferences#mw-prefsection-betafeatures"></a>
    </footer>
  </div>
</div>
```

In this `::after` node, the following css style rule is applied (got it in Style Editor|'inline style sheet # 4', beautified)
```
.mwe-popups .mwe-popups-extract[dir='ltr']:after {
    right: 0;
    background-image: -webkit-linear-gradient(to right, rgba(255, 255, 255, 0), #ffffff 50%);
    background-image: -moz-linear-gradient(to right, rgba(255, 255, 255, 0), #ffffff 50%);
    background-image: -o-linear-gradient(to right, rgba(255, 255, 255, 0), #ffffff 50%);
    background-image: linear-gradient(to right, rgba(255, 255, 255, 0), #ffffff 50%)
}
```

i.e. as you may see from the screenshot, in that rule, the property that's active is the 4th one:
if you disable it, and then disable the 2nd one (which then becomes active) the issue is fixed.

**Comment by Mottie** [comment]
Ok, try that update.

**Comment by darkred** [comment]
That's it - thanks a lot!

**Comment by darkred** [comment]
@Mottie, I think that this is more preferable:
` background-image: linear-gradient(to right, rgb(34, 34, 34, 0), rgb(34, 34, 34, 1) 50% ) !important; `
because it retains the "ellipsis" of the gradient, instead of removing it completely.
Comparison:
![2017-08-28_232613](https://user-images.githubusercontent.com/723651/29792262-899fd0b6-8c48-11e7-83ad-a7fb10ffda4b.jpg)![2017-08-28_232911](https://user-images.githubusercontent.com/723651/29792350-ca7e0c74-8c48-11e7-8a54-7c8e1cc1aecd.jpg)



I hope you agree.

**Comment by Mottie** [comment]
Done... updated on userstyles.org. Let me know if that takes care of it because I still can't see that gradient.

**Comment by darkred** [comment]
Thanks again. Yes, it's great now.
