### ISSUE TITLE
Wikipedia-Dark usercss

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/Wikipedia-Dark#37]
I just converted this userstyle into a usercss that *should* work on freestyler (not verified) and Stylus.

I added a notice on USO that we will no longer be updating Wikipedia Dark on that site.

![](https://user-images.githubusercontent.com/136959/42716772-e9a3a3fa-86c2-11e8-87d6-295e621e0e82.png)

Their HTML doesn't appear to allow header tags (`h1`, etc), so I capitalized the message.

What do you guys think? Too soon? Too harsh? Not harsh enough?

**Comment by the-j0k3r** [comment]
I dont think anyone at USo cares what we do, or whether we are harsh or not.
