### ISSUE TITLE
Random light table cell

### ISSUE THREAD

**Issue by LingMan** [StylishThemes/Wikipedia-Dark#42]
The tracklist in question is [here](https://en.wikipedia.org/wiki/Immortalized_(Disturbed_album)#Track_listing). The same can be found in the tracklists of other albums.

![immortalized disturbed album - wikipedia - mozilla firefox_004](https://user-images.githubusercontent.com/18645382/43521114-5dabace4-9595-11e8-8fb7-d4736ec766a3.png)

Again, using style version 2.0.1 and I have read the limitations section of the readme.

**Comment by Mottie** [comment]
Thanks for reporting these table issues. I took care of them because I had some time this morning. Next time you find similar problems please provide a pull request.
