### ISSUE TITLE
Some backgrounds are still white

### ISSUE THREAD

**Issue by S6066** [StylishThemes/Wikipedia-Dark#43]
https://fr.wiktionary.org/wiki/superlatif

`.ns-0 #mw-content-text div:not(.toctitle) > h2` elements have a white background
`.ns-0 ol li, .ns-0 ol li li` too, same with ul's

**Comment by Mottie** [comment]
Hi @S6066!

Thanks for reporting this issue. We'll get it fixed here shortly. Please note, we're not updating userstyles.org any more, so if you want the update, you'll need [Stylus](https://add0n.com/stylus.html) and to install it directly from this repostiory; eventually, we'll get the style hosted on [OpenUserCSS.org](https://openusercss.org)
