### ISSUE TITLE
Wikitable header

### ISSUE THREAD

**Issue by Poorchop** [StylishThemes/Wikipedia-Dark#44]
https://en.wikipedia.org/wiki/Mambo_Nassau

The background of "Review scores" in the table on the right of the page is unstyled. This could be solved with just the addition of `!important` to the background color rule for wikitable headers. Vanilla Wikipedia has a unique color for this row in order to differentiate it from the bordering headers so maybe that should be considered as well.

Didn't want to propose a pull without discussing this first.

**Comment by Mottie** [comment]
Hi @Poorchop!

Are you using the newest Wikipedia version from this repo (we're not updating userstyles.org anymore)?

I'm seeing this:

![](https://user-images.githubusercontent.com/136959/44700459-c0959680-aa4e-11e8-80ed-c0c14e5731c3.png)

**Comment by Poorchop** [comment]
Yeah I just installed the usercss version maybe less than a week ago alongside the github dark usercss version. I reinstalled it though and it looks the same as yours now. That's strange.
