### ISSUE TITLE
Question: How to make saka hints visible

### ISSUE THREAD

**Issue by azzamsa** [StylishThemes/Wikipedia-Dark#52]
Hi,

I am Stylish and Saka-Key user. When I use wikipedia-dark I can't see my saka-key hints, but it's okay when I use github-dark.

Github dark:

![screenshot_2019-01-24 stylishthemes wikipedia-dark](https://user-images.githubusercontent.com/17734314/51655845-068c6180-1fd1-11e9-9494-08ce99369310.png)

Wikipedia dark:

![screenshot_2019-01-24 salman the persian - wikipedia](https://user-images.githubusercontent.com/17734314/51655852-1015c980-1fd1-11e9-9e4e-7fb4ca180436.png)

Can wikipedia-dark style solve this issue ?

Thanks

Related : https://github.com/lusakasa/saka-key/issues/239

**Comment by ght** [comment]
There is a similar problem with [Vimium](https://github.com/philc/vimium) as of v1.64.4, because it  [does not use `!important` for the hint color](https://github.com/philc/vimium/blob/v1.64.4/content_scripts/vimium.css#L90).

**Comment by azzamsa** [comment]
@ght so the solution works by applying changes on vimium side. I wonder if it comes from Stylish side.

**Comment by the-j0k3r** [comment]
@ght Will adding this CSS to our style fix this issue?

**Comment by ght** [comment]
@the-j0k3r While it probably would, I would argue that this is out of scope and should be fixed in the affected extension. For Vimium there is already an issue about this (philc/vimium#2946).

From me +1 for closing this with wontfix

**Comment by azzamsa** [comment]
@ght thanks for the insight. So I just need to wait from (https://github.com/lusakasa/saka-key/issues/239) Saka side

**Comment by ght** [comment]
@azzamsa You can, but in the meantime you can also create a usercss that applies to `regexp(".*")` and fixes the color for you.
