### ISSUE TITLE
Remove 'v' prefix from version

### ISSUE THREAD

**Issue by silverwind** [StylishThemes/Wikipedia-Dark#59]
Currently this repo is set up to have `v` added to the tag (and tag message). Now I don't want to force my style on anyone, but I prefer tags to not include the 'v', so I'd like to change it, even if it's inconsistent with old tags. Anyone with me?

https://github.com/StylishThemes/Wikipedia-Dark/blob/f870779e9ced475d2a3d53abd3d091332d855a53/package.json#L24-L26

**Comment by silverwind** [comment]
This question it for all StylishThemes repos, either we consistently add `v` or not. GHD has been ommitting the 'v' since a while now, by the way.

**Comment by silverwind** [comment]
Maybe it is possible to unify past tags to the 'v'-less format with some `git filter-branch` magic, thought it would probably mean that GPG signatures on tags are lost and rewritten in process (not much of an issue).

**Comment by Mottie** [comment]
I don't think we need to worry about past tags.

**Comment by silverwind** [comment]
Really not sure what the best scheme for tags is. Semver has been preaching a 'v' prefix in 1.0, but that requirement was dropped in 2.0. Generally, the majority of projects on GitHub seems to use the 'v' and it's also the default behaviour of `npm version`. On the other hand `v1.2.3` is [not a valid semantic version](https://github.com/semver/semver/blob/master/semver.md#is-v123-a-semantic-version).

**Comment by the-j0k3r** [comment]
If the version badge on the GH readme works without it, doesnt seem like it..I mean its nice to see the latest version without having to dig too much, Then again not all repos have that.

Whatever you guys decide then.

**Comment by the-j0k3r** [comment]
>This question it for all StylishThemes repos, either we consistently add v or not. GHD has been ommitting the 'v' since a while now, by the way.

Its been omitting the v due to ver `-p` prefix being broken until ver 4.1.0, no other reason afaik.

The only issue is that the tag badges dont seem to work without the v prefix, like https://github.com/StylishThemes/GitHub-Dark-Script/blob/master/README.md which tag badge is now broken also due to purpuseful removal of the v prefix.

I mean its nice to see the latest version without having to dig too much, Then again not all repos have that tag badge, which could do, what would be nice not to have tag badges that require a v prefix to work.

>Maybe it is possible to unify past tags to the 'v'-less format with some git filter-branch magic, thought it would probably mean that GPG signatures on tags are lost and rewritten in process (not much of an issue).

Tag auto GPG signature is quite recent, so Ide not consider this a blocker for one or two signatures sake.

Whatever you guys decide really, but I'de prefer a solution that doesnt break tag badges.

**Comment by the-j0k3r** [comment]
>Generally, the majority of projects on GitHub seems to use the 'v' and it's also the default behaviour of npm version. On the other hand v1.2.3 is not a valid semantic version.

v is a tag name according to semantic versioning 1.2.3 is the semantic version, considering only tags are prefixed with this, I wonder if its initially related to tab badges in some way?

**Comment by silverwind** [comment]
So I guess Github's API also does not support v-less tags 😆 

````
$ curl -s https://api.github.com/repos/StylishThemes/GitHub-Dark/tags | jq -r '.[].name' | head
v1.21.32
v1.20.100
v1.20.99
v1.20.98
v1.20.97
v1.20.96
v1.20.95
v1.20.94
v1.20.93
v1.20.92

**Comment by silverwind** [comment]
Thinking of flipping around the prefix behaviour of `ver` one more time: https://github.com/silverwind/ver/issues/5.

**Comment by the-j0k3r** [comment]
If we need this open, please re-open.
