### ISSUE TITLE
Incorrect text color on .new tabs

### ISSUE THREAD

**Issue by HerrHulaHoop** [StylishThemes/Wikipedia-Dark#65]
Tabs that do not exist show up as blue instead of red. Pretty sure it wasn't always like this (as I would've noticed earlier). Maybe some new change made to MediaWiki or this theme broke it.

* **Browser**: Chrome
* **Operating System**: Windows
* **Link to page with the issue**: Any page without a talk page (I recommend going to the user talk page in [MediaWiki](https://www.mediawiki.org/wiki/MediaWiki) when not logged in 

**Screenshot**:
_Without theme_ -
![tab_light](https://user-images.githubusercontent.com/31934788/57177277-6fad2c00-6e80-11e9-9cdb-d5b9404b5e70.png)

_With theme_ -
![tab_dark](https://user-images.githubusercontent.com/31934788/57177276-6fad2c00-6e80-11e9-9b39-2f3d90826895.png)

**Comment by Mottie** [comment]
Hi @HerrHulaHoop!

It's difficult to style the tabs when we're including a background image. The "Discussion" tab in the screenshot doesn't have a bottom border because it's white. And making it transparent won't work because the content has a top border. So the only "easy" solution is to color the bottom border as has been done. If we really wanted to make the tabs look like the original page, then we'd have to add a non-transparent background color to the content, and make the bottom border of the tab the same color.

**Comment by HerrHulaHoop** [comment]
Sorry I didn't word the issue properly. Apologies for that. 

I am specifically talking about font colour, not background colour. When "User page" does not exist the font colour for it should be red. But when this theme is applied, the font colour turns blue irrespective of whether the page actually exists or not.

**Comment by the-j0k3r** [comment]
Would you try this.

```css
div.vectorTabs li.new:not(.selected) a, .vectorTabs li.new:not(.selected) a:visited {
	color: #a55858 !important;
}
```

**Comment by HerrHulaHoop** [comment]
@the-j0k3r Yep, that works!

![image](https://user-images.githubusercontent.com/31934788/57846340-9c066800-77f1-11e9-99de-b0197b306c86.png)

**Comment by HerrHulaHoop** [comment]
However, this issue seems to go beyond just the tabs. Here's an example of user pages being mentioned in the [recent changes page](https://en.wikipedia.org/wiki/Special:RecentChanges):
![57846635-47172180-77f2-11e9-8590-5a314cf0b09c](https://user-images.githubusercontent.com/31934788/57846834-b68d1100-77f2-11e9-9933-d4c2a7e115a2.png)
![57846663-58602e00-77f2-11e9-93af-13cfef805c37](https://user-images.githubusercontent.com/31934788/57846835-b68d1100-77f2-11e9-9461-f11a5a1963be.png)

And's here's how links to non-existent files look as well ([random page](https://en.wikipedia.org/wiki/Puteri_Muslimah_Asia) for reference, second line):
![image](https://user-images.githubusercontent.com/31934788/57847174-767a5e00-77f3-11e9-9f88-0eadecc786f4.png)
![image](https://user-images.githubusercontent.com/31934788/57847232-9a3da400-77f3-11e9-930f-0f72222b06dc.png)

Seems like something fundamental got changed as all these links used to work properly before.

**Comment by Mottie** [comment]
@the-j0k3r Please also add this selector for red text: `.mw-plusminus-neg` when you update.

@HerrHulaHoop I still see those links as red. It's just the negative numbers that are not. The selector to fix that is above.

**Comment by HerrHulaHoop** [comment]
@Mottie interesting... are you on chrome or firefox? All of my images have been from chrome.

**Comment by the-j0k3r** [comment]
> @the-j0k3r Please also add this selector for red text: `.mw-plusminus-neg` when you update.

In addition to mine?

**Comment by Mottie** [comment]
| In addition to mine?

Yes.

**Comment by the-j0k3r** [comment]
I couldn't see where `.mw-plusminus-neg` applied, but I added it anyway + fixed the non existent users/talk pages etc.
