### ISSUE TITLE
Some rows in tables not themed

### ISSUE THREAD

**Issue by SylwesterZarebski** [StylishThemes/Wikipedia-Dark#68]
Please check https://pl.wikipedia.org/wiki/Wu-Tang_Forever
Even `tr`s has `background-color:#f7f7f7;`.
I do not know if above page styling is correct, maybe it should be changed on Wikipedia's side?

Also button (th on top right of table) to hide table has `background-color:#ffffff;`.

* **Browser**:
Firefox & Waterfox
* **Operating System**:
Windows 10
* **Link to page with the issue**:
https://pl.wikipedia.org/wiki/Wu-Tang_Forever
* **Screenshot**:
![obraz](https://user-images.githubusercontent.com/1755531/57839863-ce02d480-77c7-11e9-9493-b7e378bcb473.png)

**Comment by Mottie** [comment]
Hi @SylwesterZarebski!

Thanks for reporting the problem. It's been fixed.

**Comment by SylwesterZarebski** [comment]
Thanks a lot!

**Comment by Korb** [comment]
https://en.wikipedia.org/wiki/Assassin%27s_Creed#cite_ref-gamespot_story_19-3 w/o style:
![2023-01-06_14-54-56](https://user-images.githubusercontent.com/3509797/211007806-568b4511-d290-4845-bbc6-582f59dac0ba.png)
With style:
![2023-01-06_14-55-07](https://user-images.githubusercontent.com/3509797/211007816-f5f39f35-b20d-41d6-932a-0a4cfe56bcfe.png)
Mozilla Firefox 109.0b9 (64-bit), Stylus 1.5.26 (1 September 2022), Wikipedia Dark 3.7.0.
