### ISSUE TITLE
Mobile styling

### ISSUE THREAD

**Issue by Mottie** [StylishThemes/Wikipedia-Dark#72]
This needs more work.

See: https://en.m.wikipedia.org

**Comment by the-j0k3r** [comment]
Needs a maintainer for sure. /me taps out.

**Comment by AfroThundr3007730** [comment]
Hmm styling the Minerva skin would be quite a bit of work, it seems. @the-j0k3r How much support does this style even have for non-standard (not Vector) skins anyway? Has it been tested with others, such as Monobook?

**Comment by AfroThundr3007730** [comment]
Just answered my own question. Here's how the style fares with each of the default skins.

## Vector (desktop default):
![MediaWiki Vector](https://user-images.githubusercontent.com/7613032/58758096-e5e79180-8505-11e9-901c-e9f8a95f3cab.png)

## CologneBlue:
![MediaWiki CologneBlue](https://user-images.githubusercontent.com/7613032/58758101-fa2b8e80-8505-11e9-8666-321f81376076.png)

## Minerva (mobile default):
![MediaWiki Minerva](https://user-images.githubusercontent.com/7613032/58758109-10d1e580-8506-11e9-9556-00212d13c1b8.png)

## Modern:
![MediaWiki Modern](https://user-images.githubusercontent.com/7613032/58758113-1fb89800-8506-11e9-84f0-4657d3ef6a66.png)

## MonoBook:
![MediaWiki MonoBook](https://user-images.githubusercontent.com/7613032/58758121-2f37e100-8506-11e9-8c3a-710d1d67bd02.png)

## Timeless:
![MediaWiki Timeless](https://user-images.githubusercontent.com/7613032/58758136-4e367300-8506-11e9-994b-5c92ea943829.png)

**Comment by AfroThundr3007730** [comment]
It would seem that aside from Vector (which we put the majority of our focus on), the Timeless skin fares the best as far as style coverage goes. I haven't found any obvious issues from my 10 second examination.

MonoBook and Modern aren't far behind, with some minor cleanup necessary to bring them up to standard, while CologneBlue will need a bit more work to do the same.

The Minerva skin is by far the worst of the bunch coverage-wise. I haven't dug too deeply into its structure yet, so I'm not sure how difficult it would be to style it without conflicting with elements of the Vector styling. It looks doable though..

**Comment by the-j0k3r** [comment]
If you take this on, one suggestion would be to apply a prefix that each of these selectors. For instance in GitHub Dark the mobile styles are prefixed with body[class="page responsive] <someselector(s)here>, but they also need to be withing media queries (wich some are not in GHD and then fixing some areas without breaking others is impossible, so as to avoid such wack-a-mole fix/break between mobile styles and desktop, it really is a great deal of work. Its very frustrating otherwise to even attempt to support mobile styles...

I dont wanna discourage you from taking it on, but its really not the sort of job for the faint of heart.

**Comment by silverwind** [comment]
Wikipedia has dedicated mobile domains, so you can just add a separate `-moz-document` section for `*.m.wikipedia.org` and similar domain names.

I probably would make three sections in the style:

- Styles applying only to desktop
- Styles applying only to mobile
- Styles applying to both

That way, you retain a clean separation where necessary while still having some styles shared.

**Comment by Poorchop** [comment]
This would be a massive undertaking. It would definitely be a neat addition but how many people would actually benefit from this? Does Stylus work on mobile?

**Comment by silverwind** [comment]
Stylus works on mobile Firefox but its userbase is probably too small to be significant. Other than that, there is the case of opening links to mobile Wikipedia when one prefers the Desktop version, but I'm sure there are extensions around that can just redirect to the Desktop site in those cases.

**Comment by AfroThundr3007730** [comment]
The thing is, there is a small minority of users (primarily editors, not just readers) who like to use the alternative skins. This includes Minerva, which can be used in desktop mode, like the others. So I think we should make an attempt to support them, where feasible.

**Comment by the-j0k3r** [comment]
I think this is a good time to add the autogenerator in a new re-write style for this style like v2. It would save a god deal of dev time, and the manual stuff would be the inline styles. Hey @silverwind ?

**Comment by silverwind** [comment]
Yes, I may eventually move the generator to a separate Node.js module so you could easily include it in other projects, it's not fully there yet thought.
