### ISSUE TITLE
Some table cells habe a white background

### ISSUE THREAD

**Issue by UweKeim** [StylishThemes/Wikipedia-Dark#75]
* **Browser**: Version 77.0.3831.6 (Offizieller Build) dev (64-Bit)
* **Operating System**: Windows 10 64-bit, German, 1903
* **Link to page with the issue**: https://de.wikipedia.org/wiki/Liste_von_Wiki-Software
* **Screenshot**:

![image](https://user-images.githubusercontent.com/415439/59999032-3a8faf80-9661-11e9-869b-306ea6f108cd.png)

**Comment by the-j0k3r** [comment]
Thank you for reporting this issue =) it should be fixed + 1 other issue further down that page.

 To update to v2.2.1 now [click here](https://github.com/StylishThemes/Wikipedia-Dark/raw/master/wikipedia-dark.user.css) or check for styles updates in your addon.

Thanks =)

**Comment by UweKeim** [comment]
Works perfectly, thanks a lot for your awesome speed of support.
