### ISSUE TITLE
Add wiki.archlinux.org

### ISSUE THREAD

**Issue by polyzen** [StylishThemes/Wikipedia-Dark#76]
> we could add the domain, but there is a bit more work to do to have the dark style's customization work on the archlinux site

https://github.com/StylishThemes/Wikipedia-Dark/pull/69#issuecomment-495604277

FWIW the theme looks fine to me. Perhaps the domain could be added, and then cleaned up in the future.

**Comment by Mottie** [comment]
I've updated the link colors to match the usercss settings.

**Comment by polyzen** [comment]
Thank you very much.
