### ISSUE TITLE
table.navbox.collapsible main content area background

### ISSUE THREAD

**Issue by Poorchop** [StylishThemes/Wikipedia-Dark#8]
I want to sit on this one for a little while to see if it breaks anything, since I'm not sure how reliable this selector is.

Adding `table.navbox.collapsible tr:nth-child(2) > td` [to this line](https://github.com/StylishThemes/Wikipedia-Dark/blob/c684d2db6f8ac0e94ebb418aa4afa725f0f973c2/wikipedia-dark.css#L64) does the trick - `.collapsible` seems to be key here.

[Offending element in question](https://en.wikipedia.org/wiki/Chris_Christie_presidential_campaign,_2016#Endorsements)

**Comment by Mottie** [comment]
So far this looks good too :grin:
