### ISSUE TITLE
White background in Russian Wikipedia

### ISSUE THREAD

**Issue by TotalCaesar659** [StylishThemes/Wikipedia-Dark#81]
Wikipedia in Russian has white background in boxes (https://ru.wikipedia.org/wiki/Заглавная_страница). English version is alright.
![1](https://user-images.githubusercontent.com/14265316/64121591-ec590400-cda7-11e9-9943-cfe121621461.png)

**Comment by AfroThundr3007730** [comment]
Got a fix for this, pushing in a bit.
