### ISSUE TITLE
More bugs in Russian Wikipedia

### ISSUE THREAD

**Issue by TotalCaesar659** [StylishThemes/Wikipedia-Dark#82]
There are white boxes in search pages (https://ru.wikipedia.org/w/index.php?search=чайф&title=Служебная%3AПоиск&fulltext=Найти&ns0=1)...
![1](https://user-images.githubusercontent.com/14265316/64302211-f4bd6480-cf8a-11e9-9efb-117a1b2dfc92.png)
...and correction warnings (https://ru.wikipedia.org/wiki/Чайф).
![2](https://user-images.githubusercontent.com/14265316/64302214-fb4bdc00-cf8a-11e9-8093-49c9ad845850.png)

**Comment by the-j0k3r** [comment]
hey @TotalCaesar659 

I fixed the link below and partially the link ontop but that top screenshot white bar  cant duplicate or see, so I cant fix it.

If you have the CSS for that please share.

In meanwhile Ill commit the other fixes.

**Comment by the-j0k3r** [comment]
this is how https://ru.wikipedia.org/wiki/%D0%A7%D0%B0%D0%B9%D1%84 looks here

![Screenshot_2019-09-05 Чайф — Википедия](https://user-images.githubusercontent.com/31389848/64324872-6ddaad00-cfc7-11e9-8883-b06e359a73fb.png)

and https://ru.wikipedia.org/w/index.php?search=чайф&title=Служебная%3AПоиск&fulltext=Найти&ns0=1 is 

![Screenshot_2019-09-05 Поиск «чайф» — Википедия](https://user-images.githubusercontent.com/31389848/64324942-8ea30280-cfc7-11e9-836f-92fc30105d22.png)

**Comment by TotalCaesar659** [comment]
I guess I've fixed first link [here](https://github.com/StylishThemes/Wikipedia-Dark/pull/83).
![1](https://user-images.githubusercontent.com/14265316/64341394-ea35b600-cff0-11e9-9f0e-53e52b12fe4d.png)

**Comment by TotalCaesar659** [comment]
@the-j0k3r Sorry to bother you, but I guess I've found the reason of the issue: enabled NoScript. Just FYI.

**Comment by the-j0k3r** [comment]
Thanks for that info. You using Tor and signed into this?

**Comment by TotalCaesar659** [comment]
No, I use NoScript in usual Chromium.
