### ISSUE TITLE
White table headbars in Russian Wikipedia

### ISSUE THREAD

**Issue by TotalCaesar659** [StylishThemes/Wikipedia-Dark#86]
https://ru.wikipedia.org/wiki/Мосс,_Стирлинг
![1](https://user-images.githubusercontent.com/14265316/65380704-4b47d400-dce9-11e9-98d7-e1df7f1d881c.png)

**Comment by AfroThundr3007730** [comment]
@the-j0k3r Lol, ok then, I'll split my other fixes out :)
