### ISSUE TITLE
German start page has white background blocks

### ISSUE THREAD

**Issue by UweKeim** [StylishThemes/Wikipedia-Dark#89]
### Browser

Google Chrome, Version 79.0.3941.4 (Offizieller Build) dev (64-Bit)

### Operating System

64-bit Windows 10, German.

### Link to page with the issue

https://de.wikipedia.org/wiki/Wikipedia:Hauptseite

### Screenshot

![image](https://user-images.githubusercontent.com/415439/67075010-9e973000-f18a-11e9-90a4-50b5043a8972.png)

**Comment by Mottie** [comment]
Hi @UweKeim!

Thanks for reporting this problem! It should be fixed now.

**Comment by UweKeim** [comment]
Thanks a lot, Rob, works perfectly now.
