### ISSUE TITLE
White headbar in Russian Wikipedia

### ISSUE THREAD

**Issue by TotalCaesar659** [StylishThemes/Wikipedia-Dark#90]
https://ru.wikipedia.org/wiki/Ли_Куан_Ю
![1](https://user-images.githubusercontent.com/14265316/67240156-90cafe80-f459-11e9-874d-59f5d3dc49e4.png)

**Comment by Mottie** [comment]
Hi @TotalCaesar659!

Thanks for reporting this problem! It should be fixed now.
