### ISSUE TITLE
userCSS on Cascadea in Safari 13.0.2 turning text from black.

### ISSUE THREAD

**Issue by atticusmatticus** [StylishThemes/Wikipedia-Dark#91]
After updating to the latest style of Wikipedia Dark a couple of days ago the text has not been turning white on the dark background. It was working as expected until a few days ago when I updated. Only Wikipedia Dark theme is doing this. The other themes I use from StylishThemes are working as expected with Cascadea so I don't think it's a cascadea issue.

* **Browser**: Safari 13.0.2 (Cascadea)
* **Operating System**: macOS 10.14.6
* **Link to page with the issue**: any wikipedia page
* **Screenshot**:
<img width="1680" alt="Screen Shot 2019-10-24 at 11 23 28" src="https://user-images.githubusercontent.com/20863400/67509949-4f04a880-f651-11e9-9a05-c2d17117d16c.png">

**Comment by the-j0k3r** [comment]
Hi @atticusmatticus thanks for reporting this issue to us.

You say that any wikipedia age is affected and dont provide a link, so let me show you one https://en.wikipedia.org/wiki/Main_Page

![Screenshot_2019-10-24 Wikipedia, the free encyclopedia](https://user-images.githubusercontent.com/31389848/67511660-a9285c80-f697-11e9-8e67-d26e0bc84181.png)

I cant reproduce this in that link I gave, so please provide a link where you can duplicate and that your wikipedia dark is version 2.3.19, if not upgrade to this version, still need that link if issue persists.

Thanks for understanding.

**Comment by atticusmatticus** [comment]
Here are some screenshots from this link: https://en.wikipedia.org/wiki/Main_Page

<img width="1680" alt="Screen Shot 2019-10-24 at 11 55 17" src="https://user-images.githubusercontent.com/20863400/67512093-57f77900-f655-11e9-81dd-9b134ee06372.png">
<img width="1680" alt="Screen Shot 2019-10-24 at 11 55 26" src="https://user-images.githubusercontent.com/20863400/67512094-58900f80-f655-11e9-985b-34001251b1db.png">

**Comment by the-j0k3r** [comment]
That's weird. Perhaps its time to call @mikefreuden the cascadea dev to maybe help shed some light on this issue not duplicateable is my setup.

**Comment by atticusmatticus** [comment]
Yeah I’m doing that as we speak, if it’s not a bug for anyone else it’s probably safari or cascadea. Thanks for the quick response!

**Comment by the-j0k3r** [comment]
There's a quicker way to test your side. Install Firefox/Chrome and [Stylus](https://github.com/openstyles/stylus#releases) + Wikipedia Dark and see whats up. =)

**Comment by mikefreuden** [comment]
Hey there! I got a chance to look into this and yes, it's a bug in Cascadea's end. A very dumb one at that, relating to Cascadea not correctly parsing the @-moz-document rules in some of the sections due to the newline between the @-moz-document at-rule and the actual rule. (It's fun having to reinvent the wheel on all this stuff from scratch!) Wrote a very easy fix and I'll make sure it ships in the next Cascadea update.

![Screenshot of it working](https://i.imgur.com/aF3iwlS.jpg)

**Comment by the-j0k3r** [comment]
Is this still an issue?

**Comment by atticusmatticus** [comment]
It was a bug on the cascades side that has been fixed.

**Comment by the-j0k3r** [comment]
Thanks.
