### ISSUE TITLE
White headbar in Russian Wikipedia

### ISSUE THREAD

**Issue by TotalCaesar659** [StylishThemes/Wikipedia-Dark#97]
https://ru.wikipedia.org/wiki/Ургант,_Иван_Андреевич
![1](https://user-images.githubusercontent.com/14265316/68958647-8fcd8880-07dd-11ea-9bdd-7ad28358ef58.png)

**Comment by the-j0k3r** [comment]
I have a feeling this type of issue will happen in another 200 pages, but in order to handle them properly it has to be so.

bare with me.
