### ISSUE TITLE
Background color is white instead of black

### ISSUE THREAD

**Issue by Naitreey** [StylishThemes/Wikipedia-Dark#99]
It looks like the `.mw-body` class defined white background color.

* **Browser**: Chrome Version 78.0.3904.108 (Official Build) (64-bit)
* **Operating System**: macOS
* **Link to page with the issue**: https://en.wikipedia.org/wiki/YAML
* **Screenshot**:
![Screen Shot 2019-11-23 at 4 48 25 PM](https://user-images.githubusercontent.com/10528297/69476164-4d293300-0e11-11ea-8b3f-de156259e9a1.png)

**Comment by the-j0k3r** [comment]
This is already fixed and committed just no release done yet.

**Comment by the-j0k3r** [comment]
Try again with https://github.com/StylishThemes/Wikipedia-Dark/raw/master/wikipedia-dark.user.css

**Comment by Naitreey** [comment]
Cool, I can confirm it's fixed. Thanks for the good work.

**Comment by the-j0k3r** [comment]
You're welcome.
